# Generated by Django 5.1.4 on 2025-12-16 13:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def seed_quantities(apps, schema_editor):
    MeasuredQuantity = apps.get_model("telemetry", "MeasuredQuantity")
    quantities = [
        ("temperature", "Temperature", "°C"),
        ("humidity", "Humidity", "%"),
        ("rpm", "RPM", "rpm"),
        ("noise", "Noise", "dB"),
        ("thrust", "Thrust", "N"),
        ("throttle", "Throttle", "%"),
    ]
    for key, name, unit in quantities:
        MeasuredQuantity.objects.get_or_create(key=key, defaults={"name": name, "unit": unit})


def create_default_stand(apps, schema_editor):
    Stand = apps.get_model("telemetry", "Stand")
    Stand.objects.get_or_create(name="Default Stand", defaults={"location": "", "description": "Основной стенд"})


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasuredQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MotorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(create_default_stand, migrations.RunPython.noop),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('motor_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='telemetry.motorgroup')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CsvImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('rows_processed', models.PositiveIntegerField(default=0)),
                ('rows_failed', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_imports', to='telemetry.session')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='telemetry.stand')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('stand', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SensorChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_channels', to='telemetry.measuredquantity')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='telemetry.sensor')),
            ],
            options={
                'ordering': ['sensor', 'quantity'],
                'unique_together': {('sensor', 'quantity')},
            },
        ),
        migrations.RunPython(seed_quantities, migrations.RunPython.noop),
    ]
